WebPlatformForEmbedded/Thunder

Source/ocdm/open_cdm.cpp
The logic was inverted in this case, and so the timeOut value was not
being used.
=> [OCDM] Use the timeOut value provided.

Source/ocdm/open_cdm.cpp
we see decryption errors due to wrong keyID being used when audio video streams use different keyids without this change. KeyID needs to be set atomically along with IV and encrypted data.
=> set keyID used in decrypt() calls atomically.

Source/interfaces/ITVControl.h, Source/interfaces/ProxyStubs.cpp
1. Rectangle moved from Implementation::Geometry to IGeometry
2. Implementation::Callback moved to IPlayer
3. Data type of Speed interface changed from uint32_t to int32_t to support rewind in the trickily
=> WPEPlayer Changes while making playerPlatform implementation as archive

Source/core/Trace.h
The recommended way to use '__VA_ARGS__' in variadic macros, is to
prepend it with '##', to avoid problems with some compilers when the
macro is invoked with zero variable arguments (see [1]).
Not prepending '__VA_ARGS__' with '##' may result on build errors with
some compilers. This is actually happening with calls like:
TRACE_L1("Some message with no variable arguments");
This way, replace all instances of '__VA_ARGS__' with '##__VA_ARGS__'.
Successfully build and runtime tested.
[1] https://gcc.gnu.org/onlinedocs/cpp/Variadic-Macros.html
Signed-off-by: Ricardo Silva <ricardo.silva@gbtembedded.com>
=> [TRACE] Fix usage of '__VA_ARGS__' in variadic macros

Source/ocdm/open_cdm.cpp
When reaching a ref count of zero, OpenCDMAccessor::Release() has a
return path that doesn't release the _systemLock, which causes, e.g., a
new instance creation via OpenCDMAccessor::Instance() to deadlock as
soon as it tries to grab the _systemLock again.
Fix this unbalanced use of _systemLock in OpenCDMAccessor::Release() by
making sure all code paths release the lock.
=> [OCDM] Fix missing lock Unlock() in OpenCDMAccessor::Release()

Source/ocdm/adapter/gstreamer/open_cdm_adapter.cpp
- too early buffer unmapping
- moving encryptedData
=> [OCDM] Fixes for crashes in adapter for GST

Source/jsonrpc/Channel.h
Fixes the following error:
/home/dwrobel/projects/webkit/WebPlatformForEmbedded-2/WPEFramework/Source/jsonrpc/Channel.h: In member function ‘void WPEFramework::JSONRPC::Client::Invoke(uint32_t, const string&, const PARAMETERS&, std::function<void(const RESPONSE&)>&)’:
/home/dwrobel/projects/webkit/WebPlatformForEmbedded-2/WPEFramework/Source/jsonrpc/Channel.h:422:27: error: return-statement with a value, in function returning ‘void’ [-fpermissive]
return (result);
^
/home/dwrobel/projects/webkit/WebPlatformForEmbedded-2/WPEFramework/Source/jsonrpc/Channel.h: In member function ‘void WPEFramework::JSONRPC::Client::Invoke(uint32_t, const string&, const PARAMETERS&, std::function<void(const RESPONSE&, WPEFramework::Core::JSONRPC::Message::Info)>&)’: …
=> Fix compilation error

Source/tracing/Logging.cpp
Fixes:
WPEFramework/Source/tracing/Logging.cpp:43:20: warning: format ‘%llu’ expects argument of type ‘long long unsigned int’, but argument 2 has type ‘uint64_t’ {aka ‘long unsigned int’} [-Wformat=]
printf("[%11llu us] %s\n", static_cast<uint64_t>(now.Ticks() - _baseTime), information->Data());
^
=> Correct printf() arguments

Source/core/ProcessInfo.cpp
Fixes:
- WPEFramework/Source/core/ProcessInfo.cpp:55:43: warning: passing argument 2 to restrict-qualified parameter aliases with argument 1 [-Wrestrict]
int32_t length = readlink(buffer, buffer, maxLength - 1);
~~~~~~  ^~~~~~
- protect from accessing 'buffer' memory beyond 'maxLength',
- use /proc/*/comm instead of /proc/*/status as it is easier to parse
and it doesn't involve sscanf() usage,
- always append '\0' to the returned process name.
readlink(2) documentation: http://pubs.opengroup.org/onlinepubs/9699919799/functions/readlink.html
=> Do not use aliased argument for 'restrict' parameter

Source/core/Frame.h
Fixes the following crash:
==26305==ERROR: AddressSanitizer: alloc-dealloc-mismatch (operator new [] vs free) on 0x615000010700
-     L1 [26305]: "Network connectivity established on IPv4. ip: 91.230.58.69, tz: CET-1CEST,M3.5.0,M10.5.0/3, country: PL"
[     170129 us] EVENT: Internet [91.230.58.69]
[     170346 us] EVENT: TimeZone: CET-1CEST,M3.5.0,M10.5.0/3, Country: PL, Region: , City:
-     L1 [26305]: "Sending out a SubSystem change notification. {"subsystems":{"Internet":true,"Location":true}}"
[     170758 us] Activated plugin [TimeSync]:[TimeSync]
-     L1 [26305]: "Timesync: Send data: 48 bytes"
-     L1 [26305]: "Timesync: Received data: 48 bytes"
-     L1 [26305]: "Request time diff  = 0.018794"
-     L1 [26305]: "Response time diff = 0.470260"
-     L1 [26305]: "Offset time …
=> ASAN - Fix alloc-dealloc-mismatch in FrameType class

Source/core/JSON.h
Make sure we output valid JSON on empty strings.
=> [JSON] Serialise empty unquoted strings to null

Source/interfaces/IDRM.h
Helps to fix errors on OCDM-Playready like;
error: ISO C++ forbids converting a string constant to ‘char*’
m_piCallback->OnKeyMessage((const uint8_t *) "", 0, "");
=> Constify OnKeyMessage() f_pszUrl parameter

Source/ocdm/adapter/broadcom-svp/open_cdm_adapter.cpp, Source/ocdm/adapter/gstreamer/open_cdm_adapter.cpp, Source/ocdm/adapter/open_cdm_adapter.h
In the _gstreamer_ adapter. Lower layer still gets arrays.
=> [WPE-292][ocdm][adapter] Use GstBuffer where possible.

Source/ocdm/ExtendedOpenCDMSession.h
For Fixing Issue #130
OpenCdm::Update API goes into a wait state with infinite wait.
In cases where the License Server or application provides
an Incorrect License Response blob to the opencdm update API
the caller thread gets blocked infinitely.
=> Opencdm Update API Timeout/Lockup issues.

Source/core/FileSystem.h
Before change File::Create was overwriting a file only if file was shared.
Also - now existing file is tranctuated to 0 by default.
=> Make File::Create ovewrite file if it already exists by default

Tools/JsonGenerator/JsonGenerator.py
Code was generating
#include <interfaces/jsonJsonData_PluginName.h>
instead of
#include <interfaces/json/JsonData_PluginName.h>
=> [JsonGenerator] Fixed missing slash in one of include in generated stub

Source/ocdm/adapter/gstreamer/open_cdm_adapter.cpp
@pwielders @modeveci , currently Netflix doesn't pass keyID to opencdm_gstreamer_session_decrypt (passes nullptr instead). Until the introduction of the GstBuffers this always worked. This proposed pull would restore the functionality. But... can this become an issue when switching to SVP? Should Netflix store the key ID for each session and pass along when calling opencdm_gstreamer_session_decrypt ?
=> [OCDM] allow for decryption without key ID

Source/compositorclient/Wayland/Westeros.cpp
EGL headers use WL_EGL_PLATFORM define to define some generatic typedefs
based on X11/wayland/eglfs being the protocols, if we do not include
wayland-egl.h first then WL_EGL_PLATFORM does not get defined and it
defaults to X11 or eglfs depending upon distro features, since westeros
is a wayland compositor we should be defining WL_EGL_PLATFORM first and
then including EGL headers
Fixes errors like
Source/compositorclient/Wayland/Implementation.h:119:65: error: invalid static_cast from type 'wl_egl_window* const' to type 'EGLNativeWindowType' {aka 'long uns igned int'}
ource/compositorclient/Wayland/Implementation.h:565:63: error: invalid static_cast from type 'wl_display* const' to type 'EGLNativeDisplayType' {aka '_XDisplay*'}
Signed-off-by: Khem Raj <raj.khem@gmail.com>
=> compositorclient/westeros: Include wayland-egl.h before EGL headers

Source/core/FileSystem.h
File::Create(const bool) had problems with parentheses, so instead of returning result of File::Create(const uint32_t, const bool) it was returning "exclusive" value.
This caused problems with storing config in Controller plugin and seemed to be crashing WebKitBrowser.
=> [FileSystem] Fixed problems with parentheses in File::Create

Source/compositorclient/Client.h
its using std::string, therefore C++ header should be included, newer
compilers and C++ runtimes are less forgiving than g++/libstdc++ and
complain about std::string missing
Signed-off-by: Khem Raj <raj.khem@gmail.com>
=> compositor/Client: Include <string> instead of string.h

Source/bluetooth/GATTSocket.cpp, Source/bluetooth/GATTSocket.h, Source/bluetooth/drivers/BCM43XX.cpp, Source/bluetooth/drivers/SerialDriver.h
Removed magic numbers from commands in bluetooth driver.
Also changed order of bytes in SerialDriver to correspond to the standard one.
=> [Bluetooth] Removed magic numbers from bt driver

Source/bluetooth/HCISocket.cpp, Source/core/SerialPort.cpp, Source/core/SerialPort.h
Moved actual closing of file to closed() rather than close(). This fixes problems with file descriptor being invalidated too quickly. 
Also fixed minor problems with locking
=> [SerialPort] Fixed file closing being made to early & locking problems

Source/websocket/WebSerializer.cpp
This fixes an issue where WebServer returns PNG with incorrect content-type "Content-Type: application/octet-stream". There is a duplicate entry below that returns the correct PNG content type.
=> WebSerializer: Don't treat PNG as binary.

Source/ocdm/open_cdm.cpp
It may cause error being returned from a CDM.
=> [OCDM] Skip unnecessary decrypt.

Source/ocdm/open_cdm_impl.h
with length uint8_t, the message is truncated and I get HTTP 400 response from DRM servers.
=> [OCDM] change length to uint16_t in onKeyMessage()

Source/core/IPCChannel.h
The handlers are registered after client connection. But not unregistered after connection closes or in destructor and its causing ASSERT on destruction.
https://github.com/WebPlatformForEmbedded/Thunder/blob/7214bcfcf984de5703f54ec9e129be1a65e16a8d/Source/core/IPCConnector.h#L742
I have put a fix for that.
=> [Core] Unregistering the handler in IPC server.

Source/core/CyclicBuffer.cpp
1.Fix to differentiate between full and empty buffer.
head == tail -> empty
(head + 1) == tail -> full
2. Checking the OVERWRITE flag while writing to buffer.
=> Fixes in core Cyclicbuffer

Source/core/DataBuffer.h
Added ASSERT to prevent (head == tail) condition which is considered as empty buffer.
=> [CyclicDataBuffer] Added ASSERT to prevent data overflow.

Source/core/Thread.h
Since the thread is not waiting here
https://github.com/WebPlatformForEmbedded/Thunder/blob/87966d6b7be079a2d8d2cccf52f28f17eac3cd67/Source/core/Thread.cpp#L157
because of delayed = 0, its showing undefined behaviour on destruction sometimes (hang or call of destructed class Worker function) . Added fix for that.
=> [Thread] Fix for proper destruction without hangs.

Source/ocdm/adapter/broadcom-svp/open_cdm_adapter.cpp
This aligns SVP adapter with the non-SVP one. Instead of
sending clear+enc+clear+enc+clear+enc+... subsamples to the DRM send only
encrypted ones. This also moves reponsibilty for proper subsamples handling
to GST part.
=> [OCDM] Send only encrypted chunks for decryption also in SVP path.

Source/core/Portability.cpp
Callstack grows left-to-right in array, with top of the stack (without current PC) on index 0. So we need to move all entries to the right and put PC at the beginning.
Credit @anjalirajan for reporting issue.
=> [CORE] Fixes stack reporting.

Source/WPEFramework/CMakeLists.txt
Allow configuring the THREADPOOL_COUNT in build time, which represents
the number of threads in the thread pool. Do this by exporting it via a
cmake variable with the same name and with its default value set to 4,
which was the previous hardcoded value (keeps backward compatibility).
In some use cases, namely when there are a lot of OOP plugins, during
startup the framework reaches states where all the threads in the pool
are already busy waiting for responses, etc., but those responses
themselves need a thread from the pool to complete and release the other
waiting threads. In some cases (depends on startup timings, etc.), no
more threads are available and responses start to fail, timeouts
reached, etc. The visible result is that some OOP plugins fail to
launch. These cases can only be …
=> [ThreadPool] Allow configuring THREADPOOL_COUNT in build time

Source/WPEFramework/PluginHost.cpp, Source/WPEProcess/Process.cpp
The signal handler for SIGSEGV was being installed unconditionally,
which prevents using other debug external tools (e.g. google's breakpad)
for debugging.
This way, install the signal handler for SIGSEGV only for debug builds.
Signed-off-by: Ricardo Silva <ricardo.silva@gbtembedded.com>
=> [DEBUG] Install SIGSEGV signal handler only for debug builds

Source/ocdm/open_cdm_impl.h
Seems we are not releasing OpenCDMAccessor class after use, so added support
=> OCDM: release ocdm system after use

Tools/CMakeLists.txt
This fixes the desktop (PC) build of WPEFramework
=> Only sets GENERIC_CMAKE_MODULE_PATH if not passed via command line.

Source/plugins/VirtualInput.cpp
When a Post Lookup map for a given link name (callsign) is registered in
the virtual input, IPCUserInput::LookupChanges() is called to search for
existing IPC Clients with names matching that link name, so those
clients post lookup map gets updated with the newly registered one.
This is required for the use cases where there are already IPC clients
registered when the post lookup map is registered (e.g. by the
RemoteControl plugin), or when a post lookup map is changed.
The way LookupChanges() is iterating over the registered IPC Clients is
incorrect. In particular the 'current' object type, declared as follows,
is wrong:
'Core::ProxyType<InputDataLink> current'
It's wrong because '_service[]' returns an entry in the client map which
is instead of type: …
=> [VirtualInput] Fix iteration in LookupChanges()

Source/core/Thread.cpp
The cause of the problem was identified as a possible bug within glibc. After the dlclose call, a chain of destructors gets called, which ends up being a 'pthread_join' call on a thread that has called 'pthread_exit' some time beforehand. This problem has been already noticed in previous glibc versions, with a bug report [available here.](https://bugs.launchpad.net/ubuntu/+source/eglibc/+bug/775374) It seems that either, the bug was not fixed, or this is expected behaviour.
Within that bug report, you can find a minimal working example that illustrates the issue, however the Makefile contents weren't valid. Here's the correct version:
```[makefile]
CC=gcc -g
APP_LDFLAGS = -ldl
LIB_LDFLAGS = -shared
APP_OBJS=main.o
LIB_OBJS=TestMod.o
APP:=join_test
LIB:=libTestMod.so
CFLAGS= -c -fPIC …
```
=> Fix for OCDMImplementation process not closing correctly.

Source/compositorclient/Wayland/Implementation.h, Source/compositorclient/Wayland/Westeros.cpp, Source/compositorclient/Wayland/Weston.cpp, cmake/modules/FindWestonClient.cmake
This pull request glues the Wayland pointer events in Weston.cpp and Westeros.cpp to the wpebackend-rdk when configured with wpeframework packageconfig. With these commits applied it is then possible to use the pointer to drive the web browser (previously only keyboard was functional).
There are also some fixes to FindWestonClient.cmake file.
=> Weston and Westeros wayland pointer support

Source/core/JSON.h
Fix for MC VolumeControl issue. See ticket: 
https://metrological.atlassian.net/browse/WPE-563
=> [JSON] Fix a problem with multiple null in JSON RPC response

README.md, Tools/.style.yapf, Tools/JsonGenerator/JsonGenerator.py, Tools/ProxyStubGenerator/CppParser.py, Tools/ProxyStubGenerator/Interface.py, Tools/ProxyStubGenerator/StubGenerator.py, Tools/ProxyStubGenerator/__init__.py, Tools/cmake/FindJsonGenerator.cmake.in, Tools/cmake/FindProxyStubGenerator.cmake.in
The following changes were introduced to align with Python 3 syntax:
- Adjusted the print calls.
- Empty **filter** calls are no longer evaluated as a false boolean expression.
- Changed the inheritance order in **Value** class, in order to fix the inconsistent MRO issue.
Additionally the files were reformatted to fit the pep8 standard.
=> Adjusted JsonGenerator & ProxyStubGenerator to work with Python 3.5.

Source/core/StateTrigger.h
There's a possible race condition around m_InterestCount between
different threads calling either WaitState() or WaitStateClear(), in
particular between threads incrementing it and other threads
decrementing it.
While the incrementing is done without an interlocked primitive with the
protecting mutex grabbed, the decrementing is done with an interlocked
primitive but without grabbing the mutex. This means that a thread doing
the non-interlocked incrementing might be descheduled in favor of a
thread doing the interlocked decrementing (which doesn't need to grab
the mutex), which will might result in an inconsistent value for
m_InterestCount in case the descheduled thread got interrupted after
loading the current value and before storing the incremented one.
Here's an example of the …
=> [StateTrigger] Use InterlockedIncrement(m_InterestCount) to fix race

Source/WPEFramework/Controller.cpp, Source/WPEFramework/PluginServer.h, Source/core/JSON.h, Source/plugins/JSONRPC.h
- HTTP response of failed JSONRPC requests are now more indicative of
root cause.
- Now capturing of invalid JSON is done on an earlier stage. Previously
even if the parser found errors, it was passed to further processing
as empty JSONRPC message, only to be caught when the function 
name (empty or garbage) was not matching the ones available to 
Controller service (as Controller is selected when empty Callsign is 
passed)
- There was a potential problem, that if there would be 2 plugins with
names that are overlapping (eg. "Bluetooth" and "BluetoothControl")
function ServiceMap::FromIdentifier could incorrectly report
Core::ERROR_INVALID_SIGNATURE when requesting the service with 
a longer name. This also caused different errors returned when service eg.
"xxBluetooth" and "Bluetoothxx" …
=> [WPE-591][JSONRPC] Made jsonrpc errors more informative

Source/core/IPCChannel.h
The first while loop in CloseClients(), which is used for
requesting/forcing the closing of clients that are not yet closed, is
not really iterating, but just revisiting the first entry for the whole
loop.
This happens because the incrementing 'index' is not being used to
select the current 'item', as at the beginning of each iteration the
current is always set to the first item (_clients.begin()).
Fix this by instead taking the current 'item' from the 'index' (which is
being incremented).
This is causing scenarios where the deactivation of plugins is failing
(or timing out), because the first loop in CloseClients() is not
requesting all the required closes (only on first client) and then the
second loop will wait forever for the clients to actually be closed. In
case of OOP plugins, this …
=> IPCChannel: Fix iteration on CloseClients() first loop

Source/WPEFramework/SystemInfo.cpp
The pointer variable _provisioning was not initiallized to nullptr in
the constructor.
And since c++ doesnt init pointer data types to nullptr when an instance
of the class is created. This can result in _provisioning having
junk/invalid value.
Some spordic crashes were observed, Where framework crashes on init.
While debugging it was observed that we are trying to Release() an
invalid _provisioning handle. Which is causing the crash.
=> [SystemInfo] Init _provisioning variable

Source/WPEFramework/PluginHost.cpp
When using a tracing file for the DefaultTraceCategories, the string
must be set as quoted using SetQuoted(true), otherwise the actual quotes
will show up when deserializing it and consequently cause failure to
open the tracing file.
=> [TRACING] Set string as quoted when using tracing file

Source/com/Communicator.h, Source/processcontainers/implementations/LXCImplementation/LXCImplementation.cpp, Source/processcontainers/implementations/LXCImplementation/LXCImplementation.h
There were changes in the way how plugins are started, that made
containers do not compile anymore. This pull fixes that.
Also, now more environment variables are required to be present to
correctly start a WPEProcess (previously only PATH was set to the 
container, but not really needed). That uncovered a bug in LXC, 
where environmental variables are not inherited from host even if they 
are requested in a container config file. That was fixed by implementing
this functionality on Thunder side.
In future it might be fixed from LXC side. Then the fix in Thunder will
be unneccessary, but shouldn't affect the correct LXC solution in a
conflicting way.
=> [Process Containers] Made PC work with latest Thunder
