- Source/com/Administrator.h
RPC Invoke() calls may cause that another Invoke() is triggered for the
same Administrator instance, as a result and necessary condition for
processing the first Invoke() call.
The second Invoke() call can be served by another minion (thread) if a
plugin as been configured to have more than one, but then a deadlock
will still happen, because the second Invoke() will be blocked when
grabbing the _adminLock (which is taken by the first Invoke()) and the
first Invoke (holding the lock) is waiting on the second Invoke() to
complete.
The _adminLock is being used to protect the _stubs and the _proxy maps.
For the _stubs case and the Invoke() call, it's only required to hold it
for finding the stub, not while calling the actual handler during the
Handle() call. This way, to avoid the deadlock in …
> [Core RPC] Fix use of_adminLock for the _stubs map

- Source/interfaces/CMakeLists.txt
- Source/interfaces/ISystemCommands.h
A very simple one; with just one command for the moment: USBReset.
> [WPE-221][INTERFACES] Add SystemCommands iface.

- Source/websocket/WebSerializer.cpp
I found this one a while ago while working on my Spotify client.
> [websocket] fix memetype parsing

- .gitignore
- Source/WPEFramework/WPEFramework.vcxproj
- Source/WPEFramework/WPEFramework.vcxproj.filters
- Source/WPEProcess/comprocess.vcxproj
- Source/com/com.vcxproj
- Source/core/core.vcxproj
- Source/core/core.vcxproj.filters
- Source/cryptalgo/cryptalgo.vcxproj
- Source/interfaces/Interfaces.vcxproj
- Source/ocdm/ocdm.vcxproj
- Source/plugins/plugins.vcxproj
- Source/plugins/plugins.vcxproj.filters
- Source/proxystubs/ProxyStubs.vcxproj
- Source/tracing/tracing.vcxproj
- Source/virtualinput/VirtualInput.vcxproj
- Source/websocket/websocket.vcxproj
a few changes were needed in order to build WPEframework with Visual Studio on Windows
> fix Visual Studio solution / project files

- Source/tracing/TraceUnit.cpp
Exposed API of TraceControl does not work, this fix reslove the problem related to disable/enable traces for all/selected modules.
> Fix problem related to disable/enable traces for all/selected modules

- Source/WPEFramework/PluginHost.cpp
Aid debugging on segfault situations.
> [CORE] dump backtrace on segfault

- Source/jsonrpc/Channel.h
> [JSONRPC] Make JSONRPC consisting WRT return value.

- Source/interfaces/CMakeLists.txt
- Source/interfaces/json/RemoteControlAPI.json
- Source/interfaces/json/RemoteControl_JsonData.h
Please take a look on current implementation based on our yesterday dicussion.
@sebastian I combined your output with implementation.
> [JSON INTERFACE] Add JSON Data interface for RemoteControl plugin

- Source/interfaces/CMakeLists.txt
- Source/interfaces/json/WebKitBrowserAPI.json
- Source/interfaces/json/WebKitBrowser_JsonData.h
JSON-RPC interface and structures
> [JSON-RPC IF] Add JSON-RPC interface defintion

- Source/core/JSON.h
> [JSON] Optimized 565d505

- Source/interfaces/json/JsonData_TimeSync.h
- Source/interfaces/json/TimeSyncAPI.json
JSON-RPC interface, including the new "set" method
> [Interfaces] Add JSON-RPC IF for TimeSync

- Source/core/Time.cpp
- Source/core/Time.h
> [Core] Introduce ISO8601 date format parsing

- Source/ocdm/adapter/broadcom-svp/open_cdm_adapter.cpp
- Source/ocdm/adapter/gstreamer/open_cdm_adapter.cpp
- Source/ocdm/adapter/open_cdm_adapter.h
- Source/ocdm/open_cdm.cpp
- Source/ocdm/open_cdm.h
- Source/ocdm/open_cdm_impl.h
Signed-off-by: Gurdal Oruklu <gurdal_oruklu@comcast.com>
> added keyID and keyIDlength to adapter_session_decrypt()

- Source/com/IUnknown.h
Releasing the remote process returned a non ERROR_DESTRUCTION_SUCCEEDED
status regardless of the release status itself.
Now the ReleaseRemote() status is returned, allowing the caller of
the Release() method to react on specific rainy day scenario e.g
method's invoke timeout.
> [COM] Make release of the remote process return the invoke status

- Source/ocdm/adapter/broadcom-svp/open_cdm_adapter.cpp
If the key control block does not require a secure output buffer, we restrict the input buffer to be only GLR which can be accessed from the HOST processor. So the chage is that Webkit provides encrypted data in GLR, and then CDM provides back decrypted data in CRR which can't be accessed from the HOST processor.
> BRCM: Secbuf usage change to set input buffer in GLR, not in CRR

- Source/ocdm/open_cdm_impl.h
the result of the decrypt() call is not being returned to the callers...
> [OCDM] pass decrypt() return codes properly

- Source/core/StreamJSON.h
Added missing Send call to parent from StreamJSON.
> [Core] Added Send callback to parent in StreamJSON.

- Source/websocket/WebSocketLink.h
There was only IsWebSocket check for IsOpen. Added extra check for channel open.
> [websocket] Added extra condition for IsOpen().

- Source/core/Number.h
> [core] Assigning template value as default in NumberType.

- Source/core/Portability.cpp
Fixed the memrcpy issue  in portability .
> [Portability] Fixed the memrcpy issue.

- Source/interfaces/IDRM.h
- Source/ocdm/IOCDM.h
- Source/ocdm/open_cdm.cpp
- Source/ocdm/open_cdm.h
- Source/ocdm/open_cdm_impl.h
> [OCDM] Add DRM-specific metadata

- Source/core/Number.h
Fixed conversion issue by adding extra condition for Hexadecimal (hexadecimal base type number in 0x format was not getting parsed)
> [NumberType] Fixed parsing issue in core Number.h.

- Source/interfaces/json/BluetoothRemoteControl.json
- Remove reduntant keys (be, unsigned)
- Add new key: name
> [interfaces/json] Update BluetoothRemoteControl's audioprofile

- Source/websocket/JSONRPCLink.h
Signed-off-by: Moorthy Baskar <moorthy.baskaravenkatraman-sambamoorthy@linaro.org>
> [JSONRPC]: fix - gcc8 build errors

- Source/com/IUnknown.h
Stress testing over interface acquire/release between different
out-of-process plugins have shown that, in some very rare and hard to
reproduce cases, DropReference() would not trigger the UnregisterProxy()
and RemoteRelease() calls required to complete the interface release.
Debugging has confirmed that the issue comes from spurious failures [1]
happening in the compare_exchange_weak() used in the following piece of
code from DropReference():
[...]
} else if (newValue == 1) {
uint8_t value(REGISTERED);
if (_remoteAddRef.compare_exchange_weak(value, UNREGISTERED, std::memory_order_release, std::memory_order_relaxed) == true) {
RPC::Administrator::Instance().UnregisterProxy(const_cast<UnknownProxy&>(*this));
RemoteRelease();
result = Core::ERROR_DESTRUCTION_SUCCEEDED;
_refCount = 0;
} …
> [COMRPC] Deal with compare_exchange_weak() spurious failures in DropReference()

- Source/WPEProcess/Process.cpp
- Source/compositorclient/RPI/CMakeLists.txt
- Source/compositorclient/RPI/Implementation.cpp
[COMPOSITOR] Prepare for RPI4 (VC6) next to previous releases of RPI.
> [WPEPROCESS] Closing of the WPEProcess conatins race conditions. Fixed.

- CMakeLists.txt
- Source/com/Communicator.h
- Source/core/Process.h
- Source/processcontainers/CMakeLists.txt
- Source/processcontainers/ProcessContainer.h
- Source/processcontainers/implementations/LXCImplementation/LXCImplementation.cpp
- Source/processcontainers/implementations/LXCImplementation/LXCImplementation.h
- Source/processcontainers/implementations/RunCImplementation/RunCImplementation.cpp
- Source/processcontainers/implementations/RunCImplementation/RunCImplementation.h
Integrated RunC containers backend support for process containers.
Changes were made to launching a process. Previously arguments were
stored in a map, which prohibited setting order or parameters. Changed
this to a vector, so the order of parameters is now important. Set() was
changed to Add() to be less confusing
> [ProcessContainers] RunC Containers integration
